{Photoshop version 1.0.1, file: ULine.a.inc
  Computer History Museum, www.computerhistory.org
  This material is (C)Copyright 1990 Adobe Systems Inc.
  It may not be distributed to third parties.
  It is licensed for non-commercial use according to 
  www.computerhistory.org/softwarelicense/photoshop/ }

PROCEDURE DoMarkLine (srcPtr: Ptr;
					  dstPtr: Ptr;
					  level: INTEGER;
					  count: INTEGER); EXTERNAL;

PROCEDURE DoMultiplyMasks (srcPtr: Ptr;
						   dstPtr: Ptr;
						   count: INTEGER); EXTERNAL;
