{Photoshop version 1.0.1, file: ULine.p.inc
  Computer History Museum, www.computerhistory.org
  This material is (C)Copyright 1990 Adobe Systems Inc.
  It may not be distributed to third parties.
  It is licensed for non-commercial use according to 
  www.computerhistory.org/softwarelicense/photoshop/ }

PROCEDURE InitLineTool; EXTERNAL;

FUNCTION DoLineTool (view: TImageView): TCommand; EXTERNAL;

PROCEDURE DoLineToolOptions; EXTERNAL;
