{Photoshop version 1.0.1, file: UTable.p.inc
  Computer History Museum, www.computerhistory.org
  This material is (C)Copyright 1990 Adobe Systems Inc.
  It may not be distributed to third parties.
  It is licensed for non-commercial use according to 
  www.computerhistory.org/softwarelicense/photoshop/ }

FUNCTION DoTableCommand (view: TImageView;
						 name: Str255): TCommand; EXTERNAL;

FUNCTION DoEditTableCommand (view: TImageView): TCommand; EXTERNAL;
